/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.audit.deep;
import cn.zhuatech.audit.model.AuditLog;import cn.zhuatech.audit.repository.AuditLogRepository;import jakarta.persistence.*;import jakarta.validation.constraints.*;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.server.ResponseStatusException;import java.time.*;import java.util.*;
@Service @Transactional(readOnly=true) public class DeepDomainService{
 private final EntityManager em;private final AuditLogRepository logs;public DeepDomainService(EntityManager e,AuditLogRepository l){em=e;logs=l;}
 public Dashboard dashboard(String org){required(org,"organizationCode");return new Dashboard(engagements(org),findings(org),workpapers(org));}
 @Transactional public EngagementView create(EngagementRequest r){if(findEngagement(r.organizationCode(),r.projectNo())!=null)throw conflict("审计项目编号已存在");if(r.plannedEnd().isBefore(r.plannedStart()))throw bad("计划结束日不能早于开始日");var e=new AuditEngagement(r.organizationCode(),r.projectNo(),r.title(),r.scope(),r.riskLevel(),r.leadAuditor(),r.plannedStart(),r.plannedEnd());em.persist(e);audit("AUDIT_PROJECT","创建审计项目",e.projectNo,e.title);return view(e);}
 @Transactional public EngagementView approve(Long id){var e=engagement(id);state(e,"DRAFT");e.status="APPROVED";audit("AUDIT_PROJECT","批准审计项目",e.projectNo,e.leadAuditor);return view(e);}
 @Transactional public EngagementView start(Long id){var e=engagement(id);state(e,"APPROVED");e.status="IN_PROGRESS";audit("AUDIT_PROJECT","启动审计项目",e.projectNo,e.scopeText);return view(e);}
 @Transactional public WorkpaperView addWorkpaper(Long id,WorkpaperRequest r){var e=engagement(id);state(e,"IN_PROGRESS");if(!r.evidenceHash().matches("[a-fA-F0-9]{64}"))throw bad("证据摘要必须为64位SHA-256");var w=new AuditWorkpaper(id,r.paperNo(),r.procedure(),r.evidenceHash().toLowerCase(),r.preparer());em.persist(w);audit("AUDIT_WORKPAPER","建立底稿",r.paperNo(),r.procedure());return view(w);}
 @Transactional public WorkpaperView submitPaper(Long id){var w=paper(id);if(!"DRAFT".equals(w.status))throw conflict("只有草稿底稿可以提交复核");w.status="SUBMITTED";audit("AUDIT_WORKPAPER","提交复核",w.paperNo,w.preparer);return view(w);}
 @Transactional public WorkpaperView reviewPaper(Long id,ReviewRequest r){var w=paper(id);if(!"SUBMITTED".equals(w.status))throw conflict("只有已提交底稿可以复核");if(w.preparer.equalsIgnoreCase(r.reviewer()))throw conflict("底稿编制人与复核人必须分离");w.reviewer=r.reviewer();w.reviewNote=r.note();w.status=r.approved()?"REVIEWED":"DRAFT";audit("AUDIT_WORKPAPER",r.approved()?"复核通过":"退回底稿",w.paperNo,r.note());return view(w);}
 @Transactional public FindingView createFinding(Long id,FindingRequest r){var e=engagement(id);state(e,"IN_PROGRESS");var f=new AuditFinding(id,r.findingNo(),r.severity(),r.condition(),r.rootCause(),r.recommendation(),r.owner(),r.dueDate());em.persist(f);audit("AUDIT_FINDING","登记审计发现",f.findingNo,f.severity);return view(f);}
 @Transactional public FindingView plan(Long id,ActionPlanRequest r){var f=finding(id);if(!"OPEN".equals(f.status))throw conflict("只有待整改发现可以提交计划");f.actionPlan=r.actionPlan();f.status="REMEDIATING";audit("AUDIT_FINDING","提交整改计划",f.findingNo,r.actionPlan());return view(f);}
 @Transactional public FindingView remediate(Long id,EvidenceRequest r){var f=finding(id);if(!"REMEDIATING".equals(f.status))throw conflict("发现尚未进入整改阶段");if(!r.evidenceHash().matches("[a-fA-F0-9]{64}"))throw bad("整改证据摘要必须为64位SHA-256");f.remediationEvidenceHash=r.evidenceHash().toLowerCase();f.status="READY_FOR_VERIFY";audit("AUDIT_FINDING","提交整改证据",f.findingNo,r.evidenceHash());return view(f);}
 @Transactional public FindingView verify(Long id,VerifyRequest r){var f=finding(id);if(!"READY_FOR_VERIFY".equals(f.status))throw conflict("只有待验证发现可以复核");f.verificationNote=r.note();f.status=r.effective()?"CLOSED":"REMEDIATING";audit("AUDIT_FINDING",r.effective()?"整改验证通过":"整改验证退回",f.findingNo,r.note());return view(f);}
 @Transactional public EngagementView issueReport(Long id){var e=engagement(id);state(e,"IN_PROGRESS");long papers=count("select count(w) from AuditWorkpaper w where w.engagementId=:id",id),unreviewed=count("select count(w) from AuditWorkpaper w where w.engagementId=:id and w.status<>'REVIEWED'",id);if(papers==0||unreviewed>0)throw conflict("全部审计底稿复核通过后才能出具报告");e.status="REPORT_ISSUED";audit("AUDIT_PROJECT","出具审计报告",e.projectNo,"workpapers="+papers);return view(e);}
 @Transactional public EngagementView close(Long id){var e=engagement(id);state(e,"REPORT_ISSUED");long open=count("select count(f) from AuditFinding f where f.engagementId=:id and f.status<>'CLOSED'",id);if(open>0)throw conflict("仍有未关闭审计发现");e.status="CLOSED";audit("AUDIT_PROJECT","项目结项",e.projectNo,"全部发现已关闭");return view(e);}
 private List<EngagementView> engagements(String org){return em.createQuery("select e from AuditEngagement e where e.organizationCode=:o order by e.createdAt desc",AuditEngagement.class).setParameter("o",org).getResultList().stream().map(this::view).toList();}private List<FindingView> findings(String org){return em.createQuery("select f from AuditFinding f where f.engagementId in(select e.id from AuditEngagement e where e.organizationCode=:o) order by f.createdAt desc",AuditFinding.class).setParameter("o",org).getResultList().stream().map(this::view).toList();}private List<WorkpaperView> workpapers(String org){return em.createQuery("select w from AuditWorkpaper w where w.engagementId in(select e.id from AuditEngagement e where e.organizationCode=:o) order by w.createdAt desc",AuditWorkpaper.class).setParameter("o",org).getResultList().stream().map(this::view).toList();}
 private AuditEngagement engagement(Long id){var x=em.find(AuditEngagement.class,id);if(x==null)throw missing("审计项目不存在");return x;}private AuditWorkpaper paper(Long id){var x=em.find(AuditWorkpaper.class,id);if(x==null)throw missing("审计底稿不存在");return x;}private AuditFinding finding(Long id){var x=em.find(AuditFinding.class,id);if(x==null)throw missing("审计发现不存在");return x;}private AuditEngagement findEngagement(String o,String n){return em.createQuery("select e from AuditEngagement e where e.organizationCode=:o and e.projectNo=:n",AuditEngagement.class).setParameter("o",o).setParameter("n",n).getResultStream().findFirst().orElse(null);}private long count(String q,Long id){return em.createQuery(q,Long.class).setParameter("id",id).getSingleResult();}private void state(AuditEngagement e,String s){if(!s.equals(e.status))throw conflict("当前审计项目状态不能执行该操作");}private void audit(String m,String a,String n,String d){logs.save(new AuditLog(m,a,n,"audit-domain",d));}private void required(String v,String n){if(v==null||v.isBlank())throw bad(n+"不能为空");}private ResponseStatusException bad(String m){return new ResponseStatusException(HttpStatus.BAD_REQUEST,m);}private ResponseStatusException conflict(String m){return new ResponseStatusException(HttpStatus.CONFLICT,m);}private ResponseStatusException missing(String m){return new ResponseStatusException(HttpStatus.NOT_FOUND,m);}
 private EngagementView view(AuditEngagement e){return new EngagementView(e.id,e.organizationCode,e.projectNo,e.title,e.scopeText,e.riskLevel,e.leadAuditor,e.status,e.plannedStart,e.plannedEnd,e.version);}private WorkpaperView view(AuditWorkpaper w){return new WorkpaperView(w.id,w.engagementId,w.paperNo,w.procedureText,w.evidenceHash,w.preparer,w.reviewer,w.status,w.reviewNote);}private FindingView view(AuditFinding f){return new FindingView(f.id,f.engagementId,f.findingNo,f.severity,f.conditionText,f.rootCause,f.recommendation,f.owner,f.dueDate,f.status,f.actionPlan,f.remediationEvidenceHash,f.verificationNote);}
 public record EngagementRequest(@NotBlank String organizationCode,@NotBlank String projectNo,@NotBlank String title,@NotBlank String scope,@NotBlank String riskLevel,@NotBlank String leadAuditor,@NotNull LocalDate plannedStart,@NotNull LocalDate plannedEnd){}public record WorkpaperRequest(@NotBlank String paperNo,@NotBlank String procedure,@NotBlank String evidenceHash,@NotBlank String preparer){}public record ReviewRequest(@NotBlank String reviewer,@NotBlank String note,boolean approved){}public record FindingRequest(@NotBlank String findingNo,@NotBlank String severity,@NotBlank String condition,@NotBlank String rootCause,@NotBlank String recommendation,@NotBlank String owner,@NotNull LocalDate dueDate){}public record ActionPlanRequest(@NotBlank String actionPlan){}public record EvidenceRequest(@NotBlank String evidenceHash){}public record VerifyRequest(boolean effective,@NotBlank String note){}
 public record EngagementView(Long id,String organizationCode,String projectNo,String title,String scope,String riskLevel,String leadAuditor,String status,LocalDate plannedStart,LocalDate plannedEnd,long version){}public record WorkpaperView(Long id,Long engagementId,String paperNo,String procedure,String evidenceHash,String preparer,String reviewer,String status,String reviewNote){}public record FindingView(Long id,Long engagementId,String findingNo,String severity,String condition,String rootCause,String recommendation,String owner,LocalDate dueDate,String status,String actionPlan,String evidenceHash,String verificationNote){}public record Dashboard(List<EngagementView> engagements,List<FindingView> findings,List<WorkpaperView> workpapers){}
}
