/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.audit.deep;import cn.zhuatech.audit.common.ApiResponse;import jakarta.validation.Valid;import org.springframework.web.bind.annotation.*;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@RestController @RequestMapping("/api/admin/audit-ops") public class DeepAdminController{private final DeepDomainService s;/**
                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                            */
public DeepAdminController(DeepDomainService s){this.s=s;}/**
                                                                                                                                                                                      * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                      */
@PostMapping("/engagements/{id}/approve")ApiResponse<?> approve(@PathVariable Long id){return ApiResponse.ok(s.approve(id));}/**
                                                                                                                                                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                   */
@PostMapping("/workpapers/{id}/review")ApiResponse<?> review(@PathVariable Long id,@Valid @RequestBody DeepDomainService.ReviewRequest r){return ApiResponse.ok(s.reviewPaper(id,r));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         */
@PostMapping("/findings/{id}/verify")ApiResponse<?> verify(@PathVariable Long id,@Valid @RequestBody DeepDomainService.VerifyRequest r){return ApiResponse.ok(s.verify(id,r));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        */
@PostMapping("/engagements/{id}/issue-report")ApiResponse<?> report(@PathVariable Long id){return ApiResponse.ok(s.issueReport(id));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             */
@PostMapping("/engagements/{id}/close")ApiResponse<?> close(@PathVariable Long id){return ApiResponse.ok(s.close(id));}}
