/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.audit.deep;import cn.zhuatech.audit.common.ApiResponse;import jakarta.validation.Valid;import org.springframework.web.bind.annotation.*;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@RestController @RequestMapping("/api/audit-ops") public class DeepDomainController{private final DeepDomainService s;/**
                                                                                                                       * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                       */
public DeepDomainController(DeepDomainService s){this.s=s;}/**
                                                                                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                  */
@GetMapping("/dashboard")ApiResponse<?> dashboard(@RequestParam String organizationCode){return ApiResponse.ok(s.dashboard(organizationCode));}/**
                                                                                                                                                                                                                                                                                                                                 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                 */
@PostMapping("/engagements")ApiResponse<?> create(@Valid @RequestBody DeepDomainService.EngagementRequest r){return ApiResponse.ok(s.create(r));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  */
@PostMapping("/engagements/{id}/start")ApiResponse<?> start(@PathVariable Long id){return ApiResponse.ok(s.start(id));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         */
@PostMapping("/engagements/{id}/workpapers")ApiResponse<?> paper(@PathVariable Long id,@Valid @RequestBody DeepDomainService.WorkpaperRequest r){return ApiResponse.ok(s.addWorkpaper(id,r));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       */
@PostMapping("/workpapers/{id}/submit")ApiResponse<?> submit(@PathVariable Long id){return ApiResponse.ok(s.submitPaper(id));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     */
@PostMapping("/engagements/{id}/findings")ApiResponse<?> finding(@PathVariable Long id,@Valid @RequestBody DeepDomainService.FindingRequest r){return ApiResponse.ok(s.createFinding(id,r));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  */
@PostMapping("/findings/{id}/action-plan")ApiResponse<?> plan(@PathVariable Long id,@Valid @RequestBody DeepDomainService.ActionPlanRequest r){return ApiResponse.ok(s.plan(id,r));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */
@PostMapping("/findings/{id}/remediate")ApiResponse<?> remediate(@PathVariable Long id,@Valid @RequestBody DeepDomainService.EvidenceRequest r){return ApiResponse.ok(s.remediate(id,r));}}
