/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.audit.deep;
import jakarta.persistence.*;import java.time.*;

@Entity @Table(name="ia_engagements",uniqueConstraints=@UniqueConstraint(columnNames={"organizationCode","projectNo"}))
class AuditEngagement{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;@Version long version;@Column(nullable=false,length=40)String organizationCode;@Column(nullable=false,length=50)String projectNo;@Column(nullable=false,length=160)String title;@Column(nullable=false,length=500)String scopeText;@Column(nullable=false,length=20)String riskLevel;@Column(nullable=false,length=50)String leadAuditor;@Column(nullable=false,length=20)String status="DRAFT";LocalDate plannedStart;LocalDate plannedEnd;LocalDateTime createdAt;protected AuditEngagement(){}AuditEngagement(String o,String n,String t,String s,String r,String l,LocalDate b,LocalDate e){organizationCode=o;projectNo=n;title=t;scopeText=s;riskLevel=r;leadAuditor=l;plannedStart=b;plannedEnd=e;createdAt=LocalDateTime.now();}}
@Entity @Table(name="ia_workpapers",uniqueConstraints=@UniqueConstraint(columnNames={"engagementId","paperNo"}))
class AuditWorkpaper{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;@Version long version;@Column(nullable=false)Long engagementId;@Column(nullable=false,length=50)String paperNo;@Column(nullable=false,length=300)String procedureText;@Column(nullable=false,length=64)String evidenceHash;@Column(nullable=false,length=50)String preparer;@Column(length=50)String reviewer;@Column(nullable=false,length=20)String status="DRAFT";@Column(length=500)String reviewNote;LocalDateTime createdAt;protected AuditWorkpaper(){}AuditWorkpaper(Long e,String n,String p,String h,String u){engagementId=e;paperNo=n;procedureText=p;evidenceHash=h;preparer=u;createdAt=LocalDateTime.now();}}
@Entity @Table(name="ia_findings",uniqueConstraints=@UniqueConstraint(columnNames={"engagementId","findingNo"}))
class AuditFinding{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;@Version long version;@Column(nullable=false)Long engagementId;@Column(nullable=false,length=50)String findingNo;@Column(nullable=false,length=20)String severity;@Column(nullable=false,length=500)String conditionText;@Column(nullable=false,length=300)String rootCause;@Column(nullable=false,length=500)String recommendation;@Column(nullable=false,length=50)String owner;LocalDate dueDate;@Column(nullable=false,length=25)String status="OPEN";@Column(length=500)String actionPlan;@Column(length=64)String remediationEvidenceHash;@Column(length=500)String verificationNote;LocalDateTime createdAt;protected AuditFinding(){}AuditFinding(Long e,String n,String s,String c,String cause,String rec,String o,LocalDate due){engagementId=e;findingNo=n;severity=s;conditionText=c;rootCause=cause;recommendation=rec;owner=o;dueDate=due;createdAt=LocalDateTime.now();}}
